"use client";

/* Client-boundary re-exports of the complete @vibe/core catalog so server
   components can render real Vibe components directly.
   Import from "@/components/ui/vibe" (raw catalog) or "@/components/ui"
   (curated design system — preferred). */
export {
  Accordion,
  AccordionItem,
  AlertBanner,
  AlertBannerButton,
  AlertBannerLink,
  AlertBannerText,
  AttentionBox,
  Avatar,
  AvatarGroup,
  Badge as VibeBadge,
  Box,
  BreadcrumbItem,
  BreadcrumbMenu,
  BreadcrumbMenuItem,
  BreadcrumbsBar,
  Button,
  ButtonGroup,
  Checkbox,
  Chips,
  Clickable,
  ColorPicker,
  Combobox,
  Counter,
  DatePicker,
  Dialog,
  DialogContentContainer,
  Divider,
  Dropdown,
  EditableHeading,
  EditableText,
  EmptyState,
  ExpandCollapse,
  Flex,
  FormattedNumber,
  Heading,
  HiddenText,
  Icon,
  IconButton,
  Label,
  LayerProvider,
  Link,
  List,
  ListItem,
  ListItemAvatar,
  ListItemIcon,
  ListTitle,
  Loader,
  Menu,
  MenuButton,
  MenuDivider,
  MenuGridItem,
  MenuItem,
  MenuItemButton,
  MenuTitle,
  Modal,
  ModalBasicLayout,
  ModalContent,
  ModalFooter,
  ModalFooterWizard,
  ModalHeader,
  ModalMedia,
  ModalMediaLayout,
  ModalSideBySideLayout,
  MultiStepIndicator,
  NumberField,
  ProgressBar,
  RadioButton,
  Search,
  Skeleton,
  Slider,
  SplitButton,
  SplitButtonMenu,
  Steps,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  TabsContext,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHeader,
  TableHeaderCell,
  TableRow,
  TableRowMenu,
  TableVirtualizedBody,
  Text,
  TextArea,
  TextField,
  TextWithHighlight,
  ThemeProvider,
  Tipseen,
  TipseenContent,
  Toast,
  ToastButton,
  ToastLink,
  Toggle,
  Tooltip,
  TransitionView,
  VirtualizedGrid,
  VirtualizedList,
} from "@vibe/core";

export type { TableColumn } from "@vibe/core";
